# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(636, 565)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setContentsMargins(0, 2, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.MainContainer = QtWidgets.QVBoxLayout()
        self.MainContainer.setObjectName("MainContainer")
        self.InputContainer = QtWidgets.QVBoxLayout()
        self.InputContainer.setContentsMargins(10, 10, 10, 10)
        self.InputContainer.setSpacing(5)
        self.InputContainer.setObjectName("InputContainer")
        self.UrlContainer = QtWidgets.QWidget(self.centralwidget)
        self.UrlContainer.setBaseSize(QtCore.QSize(10, 0))
        self.UrlContainer.setObjectName("UrlContainer")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.UrlContainer)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.url = QtWidgets.QLabel(self.UrlContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.url.sizePolicy().hasHeightForWidth())
        self.url.setSizePolicy(sizePolicy)
        self.url.setBaseSize(QtCore.QSize(10, 0))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.url.setFont(font)
        self.url.setToolTip("")
        self.url.setObjectName("url")
        self.horizontalLayout.addWidget(self.url)
        self.TextUrl = QtWidgets.QLineEdit(self.UrlContainer)
        self.TextUrl.setBaseSize(QtCore.QSize(10, 0))
        self.TextUrl.setObjectName("TextUrl")
        self.horizontalLayout.addWidget(self.TextUrl)
        self.InputContainer.addWidget(self.UrlContainer)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.InputContainer.addWidget(self.line)
        self.UrlTypeContainer = QtWidgets.QWidget(self.centralwidget)
        self.UrlTypeContainer.setMinimumSize(QtCore.QSize(200, 0))
        self.UrlTypeContainer.setMaximumSize(QtCore.QSize(500, 16777215))
        self.UrlTypeContainer.setBaseSize(QtCore.QSize(10, 0))
        self.UrlTypeContainer.setObjectName("UrlTypeContainer")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.UrlTypeContainer)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.UrlTypeContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setBaseSize(QtCore.QSize(10, 0))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.TypeSelectbox = QtWidgets.QComboBox(self.UrlTypeContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TypeSelectbox.sizePolicy().hasHeightForWidth())
        self.TypeSelectbox.setSizePolicy(sizePolicy)
        self.TypeSelectbox.setBaseSize(QtCore.QSize(10, 0))
        self.TypeSelectbox.setObjectName("TypeSelectbox")
        self.horizontalLayout_2.addWidget(self.TypeSelectbox)
        self.InputContainer.addWidget(self.UrlTypeContainer, 0, QtCore.Qt.AlignRight)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.InputContainer.addWidget(self.line_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.DirText = QtWidgets.QLabel(self.centralwidget)
        self.DirText.setBaseSize(QtCore.QSize(10, 0))
        self.DirText.setObjectName("DirText")
        self.horizontalLayout_4.addWidget(self.DirText)
        self.DirSelectButton = QtWidgets.QPushButton(self.centralwidget)
        self.DirSelectButton.setBaseSize(QtCore.QSize(10, 0))
        self.DirSelectButton.setObjectName("DirSelectButton")
        self.horizontalLayout_4.addWidget(self.DirSelectButton)
        self.horizontalLayout_4.setStretch(0, 1)
        self.InputContainer.addLayout(self.horizontalLayout_4)
        self.MainContainer.addLayout(self.InputContainer)
        self.DebugText = QtWidgets.QTextEdit(self.centralwidget)
        self.DebugText.setReadOnly(True)
        self.DebugText.setObjectName("DebugText")
        self.MainContainer.addWidget(self.DebugText)
        self.ButtonGroups = QtWidgets.QWidget(self.centralwidget)
        self.ButtonGroups.setBaseSize(QtCore.QSize(10, 0))
        self.ButtonGroups.setObjectName("ButtonGroups")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.ButtonGroups)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.DownloadButton = QtWidgets.QPushButton(self.ButtonGroups)
        self.DownloadButton.setBaseSize(QtCore.QSize(10, 0))
        self.DownloadButton.setObjectName("DownloadButton")
        self.horizontalLayout_5.addWidget(self.DownloadButton)
        self.CancelButton = QtWidgets.QPushButton(self.ButtonGroups)
        self.CancelButton.setBaseSize(QtCore.QSize(10, 0))
        self.CancelButton.setObjectName("CancelButton")
        self.horizontalLayout_5.addWidget(self.CancelButton)
        self.MainContainer.addWidget(self.ButtonGroups, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_3.addLayout(self.MainContainer)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 636, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.url.setText(_translate("MainWindow", "Url:"))
        self.label_2.setText(_translate("MainWindow", "Type:"))
        self.DirText.setText(_translate("MainWindow", "Please Select a Folder"))
        self.DirSelectButton.setText(_translate("MainWindow", "Select"))
        self.DownloadButton.setText(_translate("MainWindow", "Download"))
        self.CancelButton.setText(_translate("MainWindow", "Cancel"))
